### 2.1 내장 시퀀스 개요
#### 컨테이너 시퀀스  
- 서로 다른 자료형의 항목들을 담을 수 있는 list, tuple, collections, deque형  

#### 균일 시퀀스
- 단 하나의 자료형만 담을 수 있는 str, bytes, bytearray, memoryview, array.array형

#### 가변 시퀀스
- list, bytearray, array.array, collections.deque, memoryview 형

#### 불변 시퀀스
- tuple, str, bytes 형

### 2.2 지능형 리스트와 제너레이터 표현식

In [ ]:
import timeit

TIMES = 10000

SETUP = """
symbols = '$¢£¥€¤'
def non_ascii(c):
    return c > 127
"""

def clock(label, cmd):
    res = timeit.repeat(cmd, setup=SETUP, number=TIMES)
    print(label, *('{:.3f}'.format(x) for x in res))

clock('listcomp        :', '[ord(s) for s in symbols if ord(s) > 127]')
clock('listcomp + func :', '[ord(s) for s in symbols if non_ascii(ord(s))]')
clock('filter + lambda :', 'list(filter(lambda c: c > 127, map(ord, symbols)))')
clock('filter + func   :', 'list(filter(non_ascii, map(ord, symbols)))')


In [ ]:
colors = ["black", "white"]
sizes = ["S", "M", "L"]
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

In [ ]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)
import array
array.array("I", (ord(symbol) for symbol in symbols))

In [ ]:
colors = ["black", "white"]
sizes = ["S", "M", "L"]
for tshirt in ("%s %s" %(c,s) for c in colors for s in sizes):
    print(tshirt)

### 2.3 튜플은 단순한 불변 리스트가 아니다.
#### 2.3.1 레코드로서의 튜플

In [ ]:

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
travel_ids = [("USA", "31195855"),("BRA", "CE342567"), ("ESP", "XDA205856")]
for passport in sorted(travel_ids):
    print("%s/%s"% passport)
    print("{0}/{1}".format(*passport))

for country, _ in travel_ids:
    print(country)

#### 2.3.2 튜플 언패킹

In [ ]:
lax_coordinates =(33.9425, - 118.408056)
latitude, longitude =lax_coordinates # 튜플 언패킹
print (latitude)
print (longitude)

In [ ]:
divmod(20,8)
t= (20,8)
divmod(*t)
quotient, remainder = divmod(*t)
print (quotient, remainder)

In [ ]:
import os
_, filename = os.path.split("/home/luciano/.ssh/idrsa.pub")
filename

_ 와 같은 더미 변수를 플레이스홀더로 사용해서 관심 없는 부분은 언패킹할 때 무시할 수 있다.

In [ ]:
a, b, *rest = range(5)
print ((a, b, rest))
a, b, *rest = range(3)
print ((a, b, rest))
a, b, *rest =  range(2)
print ((a, b, rest))

In [ ]:
a, *body, c, d = range(5)
print((a, body, c,d))
*head ,b, c, d = range(5)
print((head ,b, c, d))


#### 2.3.3 내포된 튜플 언패킹

In [ ]:
metro_areas = [
    ("Tokyo", "JP", 36.933, (35.689722, 139.691667)),
    ("Delhi NCR", "IN", 21.935, (28.613889, 77.208889)),
    ("Mexico City", "MX", 20.142, (19.433333, -99.133333)),
    ("New York-Newark", "US", 20.104, (40.808611, -74.020386)),
    ("Sao Paulo", "BR", 19.649, (-23.547778, -46.635833)),    
]

print ("{:15} | {:^9} | {:^9}".format("", "lat. ", "long. "))
fmt = "{:15} | {:9.4f} | {:9.4f}"
for name, cc, pop, (latitued, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

#### 2.3.4 명명된 튜플

In [ ]:
from collections import namedtuple
City = namedtuple("City", "name country population coordinates")
tokyo = City("Tokyo", "JP", 36.933, (35.689722, 139.691667))
print (tokyo)
print (tokyo.population)
print (tokyo.coordinates)
print (tokyo[1])

In [ ]:
City._fields
LatLong = namedtuple("LatLong", "lat long")
delhi_data = ("Delhi NCR", "IN", 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
print (delhi)
delhi._asdict()
for key, value in delhi._asdict().items():
    print (key + ":", value)

#### 2.3.5 불변 리스트로서의 튜플

### 2.4 슬라이싱  
#### 2.4.1 슬라이스 범위 지정시에 마지막 항목이 포함되지 않는 이유

In [ ]:
l = [10, 20, 30, 40, 50, 60]
print (l[:2])
print (l[2:])
print (l[:3]) # 3번 인덱스에서 분할
print (l[3:])

#### 2.4.2 슬라이스 객체

In [ ]:
s = "bicycle"
print (s[::3])
print (s[::-1])
print (s[::-2])

#### 2.4.3  다차원 슬라이싱과 생략 기호

#### 2.4.4 슬라이스에 할당하기

In [ ]:
l = list(range(10))
print (l)
print (l[2:5])
l[2:5] = [20, 30]
print (l)
del l[5:7]
print (l)

l[3::2] = [11,22]
print (l)

#l[2:5] = 100
l[2:5] = [100]
print (l)

### 2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기

In [ ]:
l = [1, 2, 3]
print (l*5)
print (5*"abcd")

#### 2.5.1 리스트의 리스트 만들기

In [ ]:
board = [['_']*3 for i in range(3)]
print (board)
board[1][2] = 'X'
print (board)

board = []
for i in range(3):
    row = ["_"] *3
    board.append(row)
print (board)
board[1][2] = 'X'
print (board)

In [ ]:
weird_board = [['_'] * 3 ] *3
print (weird_board)
weird_board[1][2] ='0'
print (weird_board)

row = ['_'] *3
board = []
for i in range(3):
    board.append(row)
print (board)
board[1][2] ='0'
print (board)

### 2.6 시퀀스의 복합 할당

In [ ]:
l = [1,2,3]
print (id(l))
l *= 2
print(l)
print (id(l))

t = (1,2,3)
print (id(t))
t *= 2
print (id(t))

In [ ]:
t = (1,2,[30, 40])
t[2] += [50, 60]

In [ ]:
print (t)

### 2.7 list.sort() 와 sorted 내장함수

In [15]:
fruits = ['grape', 'rasberry', 'apple', 'banana']
print (fruits)
print (sorted(fruits))
print (sorted(fruits, reverse= True))
print (sorted(fruits,key= len))
print (sorted(fruits,key= len, reverse = True))
print (fruits)
fruits.sort()
print (fruits)

['grape', 'rasberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'rasberry']
['rasberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'rasberry']
['rasberry', 'banana', 'grape', 'apple']
['grape', 'rasberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'rasberry']


### 2.8 정렬된 시퀀스를 bisect로 관리하기
#### 2.8.1  bisect()로 검색하기

In [1]:
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = "{0:2d} @ {1:2d}    {2}{0:<2d}"

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position *"  |"
        print(ROW_FMT.format(needle, position, offset))
        
if __name__ == "__main__":
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

print ("DEMO:", bisect_fn.__name__)
print ("haystack ->", " ".join("%2d" % n for n in HAYSTACK))
demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [2]:
def grade(score, breakpoints=[60,70,80,90], grades="FDCBA"):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

print ([grade(score) for score in [33,99,77,70,89,90,100]])

['F', 'A', 'C', 'C', 'B', 'A', 'A']


#### 2.8.2  bisect.insort()로 삽입하기

In [3]:
import bisect
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print("%2d ->" % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


### 2.9 리스트가 답이 아닐 때  
- 리스트의 양쪽 끝에 항목을 계속 추가하거나 삭제하면서 FIFO나 LIFO데이터 구조를 구현할 때는 데크(deque)가 더 빠르다. 

#### 2.9.1 배열
- 리스트 안에 숫자만 들어있다면 배열(array.array)이 리스트보다 훨씬 더 효율적이다.

In [10]:
from array import array
from random import random
floats = array('d', (random() for i in range (10**7)))
print (floats[-1])
fp = open('floats.bin', 'wb')
floats.tofile(fp) # 모든 항목을 파일 fp에 쓴다. 데이터는 머신에 특화된 이진 포맷으로 저장된다.
fp.close()

floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # 파일 객체 fp에서 10**7개의 항목을 읽어온다음 floats2의 배열에 추가한다.
fp.close()
print (floats2[-1])

print (floats2 == floats)

# sort
a = array.array(a.typecode, sorted(a))
print (floats.typecode)

0.23568508397572463
0.23568508397572463
True


AttributeError: type object 'array.array' has no attribute 'array'

#### 2.9.2 메모리 뷰  
- 메모리 뷰 내장 클래스는 공유 메모리 시퀀스형으로서 bytes를 복사하지 않고 배열의 슬라이스를 다룰 수 있게 해준다.

In [32]:
import array
numbers =  array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print (len(memv))
print (memv[0])
memv_oct = memv.cast('B')
memv_oct.tolist()
memv_oct[5] =4
print (numbers)

5
-2
array('h', [-2, -1, 1024, 1, 2])


#### 2.9.3 NumPy와 SciPy

In [33]:
import numpy
a = numpy.arange(12)
print (a)
print (type(a))
print (a.shape)
a.shape = 3,4
print (a)
print (a[2])
print (a[2,1])
print (a[:, 1])
print (a.transpose()) # 행과 열을 바꾼다.

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### 2.9.4 데크 및 기타 큐
- 양쪽 끝에 추가나 제거하는 연산에 최적화 되어 있기 떄문에 중간 항목을 삭제하는 연산은 그리 빠르지 않다.

In [43]:
from collections import deque
dq = deque(range(10), maxlen=10)
print (dq)
dq.rotate(3)
print (dq)
dq.rotate(-4)
print (dq)
dq.appendleft(-1)
print (dq)
dq.extend([11,22,33])
print (dq)
dq.extendleft([10,20,30,40])
print (dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
